version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./walmart_iq.db
      - DEBUG=True
      - LOG_LEVEL=INFO
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
      - backend_data:/app/data
    networks:
      - walmart-iq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - walmart-iq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add database service for production
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: walmart_iq
  #     POSTGRES_USER: walmart_user
  #     POSTGRES_PASSWORD: secure_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - walmart-iq
  #   restart: unless-stopped

volumes:
  backend_uploads:
  backend_logs:
  backend_data:
  # postgres_data:

networks:
  walmart-iq:
    driver: bridge
